/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as EmployeeUsersRouteImport } from './routes/employee.users'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeOrdersRouteImport } from './routes/employee.orders'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as ProductsSlugIndexRouteImport } from './routes/products.$slug.index'
import { Route as ProductsSlugProofRouteImport } from './routes/products.$slug.proof'
import { Route as ProductsSlugOrderRouteImport } from './routes/products.$slug.order'
import { Route as ProductsSlugOrderIndexRouteImport } from './routes/products.$slug.order.index'
import { Route as ProductsSlugOrderTextRouteImport } from './routes/products.$slug.order.text'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const EmployeeUsersRoute = EmployeeUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeOrdersRoute = EmployeeOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => EmployeeRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugIndexRoute = ProductsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const ProductsSlugProofRoute = ProductsSlugProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const ProductsSlugOrderRoute = ProductsSlugOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const ProductsSlugOrderIndexRoute = ProductsSlugOrderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsSlugOrderRoute,
} as any)
const ProductsSlugOrderTextRoute = ProductsSlugOrderTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ProductsSlugOrderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRouteWithChildren
  '/qr': typeof QrRoute
  '/signin': typeof SigninRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/users': typeof EmployeeUsersRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/order': typeof ProductsSlugOrderRouteWithChildren
  '/products/$slug/proof': typeof ProductsSlugProofRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/products/$slug/order/text': typeof ProductsSlugOrderTextRoute
  '/products/$slug/order/': typeof ProductsSlugOrderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/order-success': typeof OrderSuccessRoute
  '/qr': typeof QrRoute
  '/signin': typeof SigninRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/users': typeof EmployeeUsersRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/$slug/proof': typeof ProductsSlugProofRoute
  '/products/$slug': typeof ProductsSlugIndexRoute
  '/products/$slug/order/text': typeof ProductsSlugOrderTextRoute
  '/products/$slug/order': typeof ProductsSlugOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRouteWithChildren
  '/qr': typeof QrRoute
  '/signin': typeof SigninRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/users': typeof EmployeeUsersRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/order': typeof ProductsSlugOrderRouteWithChildren
  '/products/$slug/proof': typeof ProductsSlugProofRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/products/$slug/order/text': typeof ProductsSlugOrderTextRoute
  '/products/$slug/order/': typeof ProductsSlugOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/create-account'
    | '/dashboard'
    | '/employee'
    | '/order-success'
    | '/products'
    | '/qr'
    | '/signin'
    | '/admin/employees'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/users'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/employee/orders'
    | '/employee/profile'
    | '/employee/users'
    | '/products/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/employee/'
    | '/products/'
    | '/products/$slug/order'
    | '/products/$slug/proof'
    | '/products/$slug/'
    | '/products/$slug/order/text'
    | '/products/$slug/order/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contact'
    | '/create-account'
    | '/order-success'
    | '/qr'
    | '/signin'
    | '/admin/employees'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/users'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/employee/orders'
    | '/employee/profile'
    | '/employee/users'
    | '/admin'
    | '/dashboard'
    | '/employee'
    | '/products'
    | '/products/$slug/proof'
    | '/products/$slug'
    | '/products/$slug/order/text'
    | '/products/$slug/order'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/create-account'
    | '/dashboard'
    | '/employee'
    | '/order-success'
    | '/products'
    | '/qr'
    | '/signin'
    | '/admin/employees'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/profile'
    | '/admin/users'
    | '/dashboard/orders'
    | '/dashboard/profile'
    | '/employee/orders'
    | '/employee/profile'
    | '/employee/users'
    | '/products/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/employee/'
    | '/products/'
    | '/products/$slug/order'
    | '/products/$slug/proof'
    | '/products/$slug/'
    | '/products/$slug/order/text'
    | '/products/$slug/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CreateAccountRoute: typeof CreateAccountRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  OrderSuccessRoute: typeof OrderSuccessRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QrRoute: typeof QrRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/employee/users': {
      id: '/employee/users'
      path: '/users'
      fullPath: '/employee/users'
      preLoaderRoute: typeof EmployeeUsersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/orders': {
      id: '/employee/orders'
      path: '/orders'
      fullPath: '/employee/orders'
      preLoaderRoute: typeof EmployeeOrdersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug/': {
      id: '/products/$slug/'
      path: '/'
      fullPath: '/products/$slug/'
      preLoaderRoute: typeof ProductsSlugIndexRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/products/$slug/proof': {
      id: '/products/$slug/proof'
      path: '/proof'
      fullPath: '/products/$slug/proof'
      preLoaderRoute: typeof ProductsSlugProofRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/products/$slug/order': {
      id: '/products/$slug/order'
      path: '/order'
      fullPath: '/products/$slug/order'
      preLoaderRoute: typeof ProductsSlugOrderRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/products/$slug/order/': {
      id: '/products/$slug/order/'
      path: '/'
      fullPath: '/products/$slug/order/'
      preLoaderRoute: typeof ProductsSlugOrderIndexRouteImport
      parentRoute: typeof ProductsSlugOrderRoute
    }
    '/products/$slug/order/text': {
      id: '/products/$slug/order/text'
      path: '/text'
      fullPath: '/products/$slug/order/text'
      preLoaderRoute: typeof ProductsSlugOrderTextRouteImport
      parentRoute: typeof ProductsSlugOrderRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeOrdersRoute: typeof EmployeeOrdersRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeUsersRoute: typeof EmployeeUsersRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeOrdersRoute: EmployeeOrdersRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeUsersRoute: EmployeeUsersRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface ProductsSlugOrderRouteChildren {
  ProductsSlugOrderTextRoute: typeof ProductsSlugOrderTextRoute
  ProductsSlugOrderIndexRoute: typeof ProductsSlugOrderIndexRoute
}

const ProductsSlugOrderRouteChildren: ProductsSlugOrderRouteChildren = {
  ProductsSlugOrderTextRoute: ProductsSlugOrderTextRoute,
  ProductsSlugOrderIndexRoute: ProductsSlugOrderIndexRoute,
}

const ProductsSlugOrderRouteWithChildren =
  ProductsSlugOrderRoute._addFileChildren(ProductsSlugOrderRouteChildren)

interface ProductsSlugRouteChildren {
  ProductsSlugOrderRoute: typeof ProductsSlugOrderRouteWithChildren
  ProductsSlugProofRoute: typeof ProductsSlugProofRoute
  ProductsSlugIndexRoute: typeof ProductsSlugIndexRoute
}

const ProductsSlugRouteChildren: ProductsSlugRouteChildren = {
  ProductsSlugOrderRoute: ProductsSlugOrderRouteWithChildren,
  ProductsSlugProofRoute: ProductsSlugProofRoute,
  ProductsSlugIndexRoute: ProductsSlugIndexRoute,
}

const ProductsSlugRouteWithChildren = ProductsSlugRoute._addFileChildren(
  ProductsSlugRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CreateAccountRoute: CreateAccountRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  OrderSuccessRoute: OrderSuccessRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QrRoute: QrRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
