/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as QrRouteImport } from './routes/qr'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProductsSlugIndexRouteImport } from './routes/products.$slug.index'
import { Route as ProductsSlugProofRouteImport } from './routes/products.$slug.proof'
import { Route as ProductsSlugOrderRouteImport } from './routes/products.$slug.order'
import { Route as ProductsSlugOrderIndexRouteImport } from './routes/products.$slug.order.index'
import { Route as ProductsSlugOrderTextRouteImport } from './routes/products.$slug.order.text'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSlugIndexRoute = ProductsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const ProductsSlugProofRoute = ProductsSlugProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const ProductsSlugOrderRoute = ProductsSlugOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const ProductsSlugOrderIndexRoute = ProductsSlugOrderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsSlugOrderRoute,
} as any)
const ProductsSlugOrderTextRoute = ProductsSlugOrderTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => ProductsSlugOrderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRouteWithChildren
  '/qr': typeof QrRoute
  '/signin': typeof SigninRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/order': typeof ProductsSlugOrderRouteWithChildren
  '/products/$slug/proof': typeof ProductsSlugProofRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/products/$slug/order/text': typeof ProductsSlugOrderTextRoute
  '/products/$slug/order/': typeof ProductsSlugOrderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/qr': typeof QrRoute
  '/signin': typeof SigninRoute
  '/products': typeof ProductsIndexRoute
  '/products/$slug/proof': typeof ProductsSlugProofRoute
  '/products/$slug': typeof ProductsSlugIndexRoute
  '/products/$slug/order/text': typeof ProductsSlugOrderTextRoute
  '/products/$slug/order': typeof ProductsSlugOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRouteWithChildren
  '/qr': typeof QrRoute
  '/signin': typeof SigninRoute
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/products/$slug/order': typeof ProductsSlugOrderRouteWithChildren
  '/products/$slug/proof': typeof ProductsSlugProofRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/products/$slug/order/text': typeof ProductsSlugOrderTextRoute
  '/products/$slug/order/': typeof ProductsSlugOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/contact'
    | '/create-account'
    | '/dashboard'
    | '/products'
    | '/qr'
    | '/signin'
    | '/products/$slug'
    | '/products/'
    | '/products/$slug/order'
    | '/products/$slug/proof'
    | '/products/$slug/'
    | '/products/$slug/order/text'
    | '/products/$slug/order/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contact'
    | '/create-account'
    | '/dashboard'
    | '/qr'
    | '/signin'
    | '/products'
    | '/products/$slug/proof'
    | '/products/$slug'
    | '/products/$slug/order/text'
    | '/products/$slug/order'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/contact'
    | '/create-account'
    | '/dashboard'
    | '/products'
    | '/qr'
    | '/signin'
    | '/products/$slug'
    | '/products/'
    | '/products/$slug/order'
    | '/products/$slug/proof'
    | '/products/$slug/'
    | '/products/$slug/order/text'
    | '/products/$slug/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CreateAccountRoute: typeof CreateAccountRoute
  DashboardRoute: typeof DashboardRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  QrRoute: typeof QrRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$slug/': {
      id: '/products/$slug/'
      path: '/'
      fullPath: '/products/$slug/'
      preLoaderRoute: typeof ProductsSlugIndexRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/products/$slug/proof': {
      id: '/products/$slug/proof'
      path: '/proof'
      fullPath: '/products/$slug/proof'
      preLoaderRoute: typeof ProductsSlugProofRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/products/$slug/order': {
      id: '/products/$slug/order'
      path: '/order'
      fullPath: '/products/$slug/order'
      preLoaderRoute: typeof ProductsSlugOrderRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/products/$slug/order/': {
      id: '/products/$slug/order/'
      path: '/'
      fullPath: '/products/$slug/order/'
      preLoaderRoute: typeof ProductsSlugOrderIndexRouteImport
      parentRoute: typeof ProductsSlugOrderRoute
    }
    '/products/$slug/order/text': {
      id: '/products/$slug/order/text'
      path: '/text'
      fullPath: '/products/$slug/order/text'
      preLoaderRoute: typeof ProductsSlugOrderTextRouteImport
      parentRoute: typeof ProductsSlugOrderRoute
    }
  }
}

interface ProductsSlugOrderRouteChildren {
  ProductsSlugOrderTextRoute: typeof ProductsSlugOrderTextRoute
  ProductsSlugOrderIndexRoute: typeof ProductsSlugOrderIndexRoute
}

const ProductsSlugOrderRouteChildren: ProductsSlugOrderRouteChildren = {
  ProductsSlugOrderTextRoute: ProductsSlugOrderTextRoute,
  ProductsSlugOrderIndexRoute: ProductsSlugOrderIndexRoute,
}

const ProductsSlugOrderRouteWithChildren =
  ProductsSlugOrderRoute._addFileChildren(ProductsSlugOrderRouteChildren)

interface ProductsSlugRouteChildren {
  ProductsSlugOrderRoute: typeof ProductsSlugOrderRouteWithChildren
  ProductsSlugProofRoute: typeof ProductsSlugProofRoute
  ProductsSlugIndexRoute: typeof ProductsSlugIndexRoute
}

const ProductsSlugRouteChildren: ProductsSlugRouteChildren = {
  ProductsSlugOrderRoute: ProductsSlugOrderRouteWithChildren,
  ProductsSlugProofRoute: ProductsSlugProofRoute,
  ProductsSlugIndexRoute: ProductsSlugIndexRoute,
}

const ProductsSlugRouteWithChildren = ProductsSlugRoute._addFileChildren(
  ProductsSlugRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CreateAccountRoute: CreateAccountRoute,
  DashboardRoute: DashboardRoute,
  ProductsRoute: ProductsRouteWithChildren,
  QrRoute: QrRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
